name: jobber # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A jobbscript (somescript) # 79 char long summary
description: |
  Example jobscript snap. Runs as "somescript"

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  jobber:
    # See 'snapcraft plugins'
    source: .
    plugin: python
    python-version: python3

apps:
    jobber:
      command: somescript
